---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubedoom
  name: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
        - protocol: TCP
          containerPort: 5900
          name: vnc

