---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-config
  labels:
    app: redmine
data:
  REDMINE_DB_POSTGRES: database-svc
  REDMINE_DB_USERNAME: testuser
  REDMINE_DB_DATABASE: testdatabase

